{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "3bfbf37b-207b-4a04-8699-cf06ba42fa06",
   "metadata": {},
   "outputs": [],
   "source": [
    "from matplotlib import pyplot as plt\n",
    "import numpy as np\n",
    "import pandas as pd\n",
    "import xarray as xr\n",
    "import zarr\n",
    "import gcsfs\n",
    "\n",
    "from dask_gateway import Gateway\n",
    "from dask.distributed import Client\n",
    "\n",
    "gateway = Gateway()\n",
    "cluster = gateway.new_cluster()\n",
    "\n",
    "cluster.scale(10)\n",
    "client = Client(cluster,timeout=\"120s\")\n",
    "cluster"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "5ba43347-9a6f-4808-9858-d59b822ea039",
   "metadata": {},
   "outputs": [],
   "source": [
    "from eofs.xarray import Eof\n",
    "import xrscipy.signal as dsp\n",
    "import math "
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 12,
   "id": "a703a3a3-4071-45be-9c8b-94895c226288",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2023-03-24 20:23:38,788 - distributed.client - ERROR - Failed to reconnect to scheduler after 120.00 seconds, closing client\n",
      "Exception in callback None()\n",
      "handle: <Handle cancelled>\n",
      "Traceback (most recent call last):\n",
      "  File \"/srv/conda/envs/notebook/lib/python3.10/site-packages/tornado/iostream.py\", line 1389, in _do_ssl_handshake\n",
      "    self.socket.do_handshake()\n",
      "  File \"/srv/conda/envs/notebook/lib/python3.10/ssl.py\", line 1342, in do_handshake\n",
      "    self._sslobj.do_handshake()\n",
      "ssl.SSLZeroReturnError: TLS/SSL connection has been closed (EOF) (_ssl.c:997)\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/srv/conda/envs/notebook/lib/python3.10/asyncio/events.py\", line 80, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"/srv/conda/envs/notebook/lib/python3.10/site-packages/tornado/platform/asyncio.py\", line 206, in _handle_events\n",
      "    handler_func(fileobj, events)\n",
      "  File \"/srv/conda/envs/notebook/lib/python3.10/site-packages/tornado/iostream.py\", line 698, in _handle_events\n",
      "    self._handle_read()\n",
      "  File \"/srv/conda/envs/notebook/lib/python3.10/site-packages/tornado/iostream.py\", line 1476, in _handle_read\n",
      "    self._do_ssl_handshake()\n",
      "  File \"/srv/conda/envs/notebook/lib/python3.10/site-packages/tornado/iostream.py\", line 1398, in _do_ssl_handshake\n",
      "    return self.close(exc_info=err)\n",
      "  File \"/srv/conda/envs/notebook/lib/python3.10/site-packages/tornado/iostream.py\", line 613, in close\n",
      "    self._signal_closed()\n",
      "  File \"/srv/conda/envs/notebook/lib/python3.10/site-packages/tornado/iostream.py\", line 643, in _signal_closed\n",
      "    self._ssl_connect_future.exception()\n",
      "asyncio.exceptions.CancelledError\n",
      "Exception in callback None()\n",
      "handle: <Handle cancelled>\n",
      "Traceback (most recent call last):\n",
      "  File \"/srv/conda/envs/notebook/lib/python3.10/site-packages/tornado/iostream.py\", line 1389, in _do_ssl_handshake\n",
      "    self.socket.do_handshake()\n",
      "  File \"/srv/conda/envs/notebook/lib/python3.10/ssl.py\", line 1342, in do_handshake\n",
      "    self._sslobj.do_handshake()\n",
      "ssl.SSLZeroReturnError: TLS/SSL connection has been closed (EOF) (_ssl.c:997)\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/srv/conda/envs/notebook/lib/python3.10/asyncio/events.py\", line 80, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"/srv/conda/envs/notebook/lib/python3.10/site-packages/tornado/platform/asyncio.py\", line 206, in _handle_events\n",
      "    handler_func(fileobj, events)\n",
      "  File \"/srv/conda/envs/notebook/lib/python3.10/site-packages/tornado/iostream.py\", line 698, in _handle_events\n",
      "    self._handle_read()\n",
      "  File \"/srv/conda/envs/notebook/lib/python3.10/site-packages/tornado/iostream.py\", line 1476, in _handle_read\n",
      "    self._do_ssl_handshake()\n",
      "  File \"/srv/conda/envs/notebook/lib/python3.10/site-packages/tornado/iostream.py\", line 1398, in _do_ssl_handshake\n",
      "    return self.close(exc_info=err)\n",
      "  File \"/srv/conda/envs/notebook/lib/python3.10/site-packages/tornado/iostream.py\", line 613, in close\n",
      "    self._signal_closed()\n",
      "  File \"/srv/conda/envs/notebook/lib/python3.10/site-packages/tornado/iostream.py\", line 643, in _signal_closed\n",
      "    self._ssl_connect_future.exception()\n",
      "asyncio.exceptions.CancelledError\n"
     ]
    }
   ],
   "source": [
    "df = pd.read_csv('https://storage.googleapis.com/cmip6/cmip6-zarr-consolidated-stores.csv')\n",
    "df.head()\n",
    "\n",
    "def get_df(invar):\n",
    "# this only needs to be created once\n",
    "    gcs = gcsfs.GCSFileSystem(token='anon')\n",
    "\n",
    "# get the path to a specific zarr store (the first one from the dataframe above)\n",
    "    zstore = invar.zstore.values[0]\n",
    "\n",
    "# create a mutable-mapping-style interface to the store\n",
    "    mapper = gcs.get_mapper(zstore)\n",
    "\n",
    "# open it using xarray and zarr\n",
    "    outvar = xr.open_zarr(mapper, consolidated=True)\n",
    "\n",
    "    return outvar\n",
    "\n",
    "#model_names=['ACCESS-CM2','ACCESS-ESM1-5','CanESM5-CanOE','CanESM5','CESM2-WACCM','CESM2',\\\n",
    "#             'CNRM-CM6-1','CNRM-ESM2-1','EC-Earth3','EC-Earth3-Veg','FGOALS-g3',\\\n",
    "#                 'FIO-ESM-2-0','HadGEM3-GC31-LL','HadGEM3-GC31-MM','IPSL-CM6A-LR','KACE-1-0-G',\\\n",
    "#                    'MIROC6','MIROC-ES2L', 'MPI-ESM1-2-LR','UKESM1-0-LL']\n",
    "\n",
    "model_names=['UKESM1-0-LL']\n",
    "\n",
    "for x in range(0,len(model_names)):\n",
    "\n",
    "\n",
    "    \n",
    "    model_name='\"'+model_names[x]+'\"'\n",
    "    experiment='\"piControl\"'\n",
    "\n",
    "    test='source_id == '+ model_name +' & activity_id==\"CMIP\" & table_id == \"Omon\" & variable_id == \"thetao\" & experiment_id == '+experiment\n",
    "\n",
    " #   theta = df.query('source_id =='+ model_name +' & table_id == \"Amon\" & variable_id == \"ts\" & experiment_id =='+ experiment+'& member_id == \"r1i1p1f1\"')\n",
    " #   tauu=df.query('source_id =='+ model_name +'& table_id == \"Amon\" & variable_id == \"tauu\" & experiment_id =='+ experiment+'& member_id == \"r1i1p1f1\"')\n",
    "    theta = df.query('source_id =='+ model_name +' & table_id == \"Amon\" & variable_id == \"ts\" & experiment_id =='+ experiment)\n",
    "   # tauu=df.query('source_id =='+ model_name +'& table_id == \"Amon\" & variable_id == \"tauu\" & experiment_id =='+ experiment)\n",
    "\n",
    "    import xesmf as xe # I use xesmf to regrid from the ocean curvelinear to lat/lon grid\n",
    "\n",
    "    theta_pi=get_df(theta)\n",
    "    theta_trop=theta_pi.sel(lon=slice(140,280)).sel(lat=slice(-15,15)).isel(time=slice(0,200*12))\n",
    "    sst_low=theta_trop['ts'].assign_coords(time=range(0,len(theta_trop.time)))\n",
    "    sst_low.load()\n",
    "    sst_low= dsp.bandpass(sst_low,1/(10*12),1/(1.5*12),dim='time')\n",
    "\n",
    "    sst_low=sst_low.transpose(\"time\", \"lon\", \"lat\")\n",
    "\n",
    "    solver = Eof(sst_low)\n",
    "\n",
    "    eofs = solver.eofs(neofs=2)\n",
    "    pcs = solver.pcs(npcs=2)\n",
    "    pcs = (pcs-pcs.mean('time'))/pcs.std('time')\n",
    "    eofs=eofs.transpose(\"lat\", \"lon\",'mode')\n",
    "    \n",
    "    model_name='\"'+model_names[x]+'\"'\n",
    "    experiment='\"ssp585\"'\n",
    "\n",
    "    test='source_id == '+ model_name +' & activity_id==\"CMIP\" & table_id == \"Omon\" & variable_id == \"thetao\" & experiment_id == '+experiment\n",
    "\n",
    " #   theta = df.query('source_id =='+ model_name +' & table_id == \"Amon\" & variable_id == \"ts\" & experiment_id =='+ experiment+'& member_id == \"r1i1p1f1\"')\n",
    " #   tauu=df.query('source_id =='+ model_name +'& table_id == \"Amon\" & variable_id == \"tauu\" & experiment_id =='+ experiment+'& member_id == \"r1i1p1f1\"')\n",
    "    theta = df.query('source_id =='+ model_name +' & table_id == \"Amon\" & variable_id == \"ts\" & experiment_id =='+ experiment)\n",
    "   # tauu=df.query('source_id =='+ model_name +'& table_id == \"Amon\" & variable_id == \"tauu\" & experiment_id =='+ experiment)\n",
    "\n",
    "    import xesmf as xe # I use xesmf to regrid from the ocean curvelinear to lat/lon grid\n",
    "\n",
    "    theta_pi=get_df(theta)\n",
    "    theta_trop=theta_pi.sel(lon=slice(140,280)).sel(lat=slice(-15,15))\n",
    "    sst_low=theta_trop['ts'].assign_coords(time=range(0,len(theta_trop.time)))\n",
    "    sst_low.load()\n",
    "    sst_low= dsp.bandpass(sst_low,1/(10*12),1/(1.5*12),dim='time')\n",
    "\n",
    "    sst_low=sst_low.transpose(\"time\", \"lon\", \"lat\")\n",
    "\n",
    "    pseudo_pcs = solver.projectField(sst_low, neofs=2)\n",
    "\n",
    "\n",
    "    E_index=(pseudo_pcs.sel(mode=0)+pseudo_pcs.sel(mode=1))#**(-1/2)\n",
    "    E_index=E_index/math.sqrt(2)\n",
    "\n",
    "    E_index.to_netcdf('C_index_proj'+model_names[x]+'_ssp585_1.nc')\n",
    "  "
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "id": "4550b885-d4fe-476c-8f90-f6d15e60970a",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "/srv/conda/envs/notebook/lib/python3.10/site-packages/xarray/coding/times.py:699: SerializationWarning: Unable to decode time axis into full numpy.datetime64 objects, continuing using cftime.datetime objects instead, reason: dates out of range\n",
      "  dtype = _decode_cf_datetime_dtype(data, units, calendar, self.use_cftime)\n",
      "/srv/conda/envs/notebook/lib/python3.10/site-packages/xarray/coding/times.py:150: SerializationWarning: Ambiguous reference date string: 950-01-01. The first value is assumed to be the year hence will be padded with zeros to remove the ambiguity (the padded reference date string is: 0950-01-01). To remove this message, remove the ambiguity by padding your reference date strings with zeros.\n",
      "  warnings.warn(warning_msg, SerializationWarning)\n",
      "/srv/conda/envs/notebook/lib/python3.10/site-packages/xarray/core/indexing.py:524: SerializationWarning: Unable to decode time axis into full numpy.datetime64 objects, continuing using cftime.datetime objects instead, reason: dates out of range\n",
      "  return np.asarray(array[self.key], dtype=None)\n",
      "/srv/conda/envs/notebook/lib/python3.10/site-packages/xarray/coding/times.py:699: SerializationWarning: Unable to decode time axis into full numpy.datetime64 objects, continuing using cftime.datetime objects instead, reason: dates out of range\n",
      "  dtype = _decode_cf_datetime_dtype(data, units, calendar, self.use_cftime)\n",
      "/srv/conda/envs/notebook/lib/python3.10/site-packages/xarray/core/indexing.py:524: SerializationWarning: Unable to decode time axis into full numpy.datetime64 objects, continuing using cftime.datetime objects instead, reason: dates out of range\n",
      "  return np.asarray(array[self.key], dtype=None)\n",
      "/srv/conda/envs/notebook/lib/python3.10/site-packages/xarray/coding/times.py:699: SerializationWarning: Unable to decode time axis into full numpy.datetime64 objects, continuing using cftime.datetime objects instead, reason: dates out of range\n",
      "  dtype = _decode_cf_datetime_dtype(data, units, calendar, self.use_cftime)\n",
      "/srv/conda/envs/notebook/lib/python3.10/site-packages/xarray/coding/times.py:699: SerializationWarning: Unable to decode time axis into full numpy.datetime64 objects, continuing using cftime.datetime objects instead, reason: dates out of range\n",
      "  dtype = _decode_cf_datetime_dtype(data, units, calendar, self.use_cftime)\n",
      "/srv/conda/envs/notebook/lib/python3.10/site-packages/xarray/core/indexing.py:524: SerializationWarning: Unable to decode time axis into full numpy.datetime64 objects, continuing using cftime.datetime objects instead, reason: dates out of range\n",
      "  return np.asarray(array[self.key], dtype=None)\n",
      "/srv/conda/envs/notebook/lib/python3.10/site-packages/xarray/coding/times.py:699: SerializationWarning: Unable to decode time axis into full numpy.datetime64 objects, continuing using cftime.datetime objects instead, reason: dates out of range\n",
      "  dtype = _decode_cf_datetime_dtype(data, units, calendar, self.use_cftime)\n",
      "/srv/conda/envs/notebook/lib/python3.10/site-packages/xarray/core/indexing.py:524: SerializationWarning: Unable to decode time axis into full numpy.datetime64 objects, continuing using cftime.datetime objects instead, reason: dates out of range\n",
      "  return np.asarray(array[self.key], dtype=None)\n",
      "/srv/conda/envs/notebook/lib/python3.10/site-packages/xarray/coding/times.py:699: SerializationWarning: Unable to decode time axis into full numpy.datetime64 objects, continuing using cftime.datetime objects instead, reason: dates out of range\n",
      "  dtype = _decode_cf_datetime_dtype(data, units, calendar, self.use_cftime)\n",
      "/srv/conda/envs/notebook/lib/python3.10/site-packages/xarray/coding/times.py:699: SerializationWarning: Unable to decode time axis into full numpy.datetime64 objects, continuing using cftime.datetime objects instead, reason: dates out of range\n",
      "  dtype = _decode_cf_datetime_dtype(data, units, calendar, self.use_cftime)\n",
      "/srv/conda/envs/notebook/lib/python3.10/site-packages/xarray/core/indexing.py:524: SerializationWarning: Unable to decode time axis into full numpy.datetime64 objects, continuing using cftime.datetime objects instead, reason: dates out of range\n",
      "  return np.asarray(array[self.key], dtype=None)\n",
      "/srv/conda/envs/notebook/lib/python3.10/site-packages/xarray/coding/times.py:699: SerializationWarning: Unable to decode time axis into full numpy.datetime64 objects, continuing using cftime.datetime objects instead, reason: dates out of range\n",
      "  dtype = _decode_cf_datetime_dtype(data, units, calendar, self.use_cftime)\n",
      "/srv/conda/envs/notebook/lib/python3.10/site-packages/xarray/coding/times.py:699: SerializationWarning: Unable to decode time axis into full numpy.datetime64 objects, continuing using cftime.datetime objects instead, reason: dates out of range\n",
      "  dtype = _decode_cf_datetime_dtype(data, units, calendar, self.use_cftime)\n",
      "/srv/conda/envs/notebook/lib/python3.10/site-packages/xarray/core/indexing.py:524: SerializationWarning: Unable to decode time axis into full numpy.datetime64 objects, continuing using cftime.datetime objects instead, reason: dates out of range\n",
      "  return np.asarray(array[self.key], dtype=None)\n",
      "/srv/conda/envs/notebook/lib/python3.10/site-packages/xarray/coding/times.py:699: SerializationWarning: Unable to decode time axis into full numpy.datetime64 objects, continuing using cftime.datetime objects instead, reason: dates out of range\n",
      "  dtype = _decode_cf_datetime_dtype(data, units, calendar, self.use_cftime)\n",
      "/srv/conda/envs/notebook/lib/python3.10/site-packages/xarray/core/indexing.py:524: SerializationWarning: Unable to decode time axis into full numpy.datetime64 objects, continuing using cftime.datetime objects instead, reason: dates out of range\n",
      "  return np.asarray(array[self.key], dtype=None)\n",
      "/srv/conda/envs/notebook/lib/python3.10/site-packages/xarray/coding/times.py:699: SerializationWarning: Unable to decode time axis into full numpy.datetime64 objects, continuing using cftime.datetime objects instead, reason: dates out of range\n",
      "  dtype = _decode_cf_datetime_dtype(data, units, calendar, self.use_cftime)\n",
      "/srv/conda/envs/notebook/lib/python3.10/site-packages/xarray/coding/times.py:699: SerializationWarning: Unable to decode time axis into full numpy.datetime64 objects, continuing using cftime.datetime objects instead, reason: dates out of range\n",
      "  dtype = _decode_cf_datetime_dtype(data, units, calendar, self.use_cftime)\n",
      "/srv/conda/envs/notebook/lib/python3.10/site-packages/xarray/core/indexing.py:524: SerializationWarning: Unable to decode time axis into full numpy.datetime64 objects, continuing using cftime.datetime objects instead, reason: dates out of range\n",
      "  return np.asarray(array[self.key], dtype=None)\n",
      "/srv/conda/envs/notebook/lib/python3.10/site-packages/xarray/coding/times.py:699: SerializationWarning: Unable to decode time axis into full numpy.datetime64 objects, continuing using cftime.datetime objects instead, reason: dates out of range\n",
      "  dtype = _decode_cf_datetime_dtype(data, units, calendar, self.use_cftime)\n",
      "/srv/conda/envs/notebook/lib/python3.10/site-packages/xarray/coding/times.py:699: SerializationWarning: Unable to decode time axis into full numpy.datetime64 objects, continuing using cftime.datetime objects instead, reason: dates out of range\n",
      "  dtype = _decode_cf_datetime_dtype(data, units, calendar, self.use_cftime)\n",
      "/srv/conda/envs/notebook/lib/python3.10/site-packages/xarray/core/indexing.py:524: SerializationWarning: Unable to decode time axis into full numpy.datetime64 objects, continuing using cftime.datetime objects instead, reason: dates out of range\n",
      "  return np.asarray(array[self.key], dtype=None)\n"
     ]
    }
   ],
   "source": [
    "df = pd.read_csv('https://storage.googleapis.com/cmip6/cmip6-zarr-consolidated-stores.csv')\n",
    "df.head()\n",
    "\n",
    "\n",
    "\n",
    "model_names=['ACCESS-CM2','ACCESS-ESM1-5','CanESM5-CanOE','CanESM5','CESM2-WACCM','CESM2',\\\n",
    "             'CNRM-CM6-1','CNRM-ESM2-1','EC-Earth3','EC-Earth3-Veg','FGOALS-g3',\\\n",
    "                 'FIO-ESM-2-0','HadGEM3-GC31-LL','HadGEM3-GC31-MM','IPSL-CM6A-LR','KACE-1-0-G',\\\n",
    "                    'MIROC6','MIROC-ES2L', 'MPI-ESM1-2-LR','UKESM1-0-LL']\n",
    "\n",
    "for x in range(0,len(model_names)):\n",
    "\n",
    "    def get_df(invar):\n",
    "# this only needs to be created once\n",
    "        gcs = gcsfs.GCSFileSystem(token='anon')\n",
    "\n",
    "# get the path to a specific zarr store (the first one from the dataframe above)\n",
    "        zstore = invar.zstore.values[0]\n",
    "\n",
    "# create a mutable-mapping-style interface to the store\n",
    "        mapper = gcs.get_mapper(zstore)\n",
    "\n",
    "# open it using xarray and zarr\n",
    "        outvar = xr.open_zarr(mapper, consolidated=True)\n",
    "\n",
    "        return outvar\n",
    "    \n",
    "    model_name='\"'+model_names[x]+'\"'\n",
    "    experiment='\"piControl\"'\n",
    "\n",
    "    test='source_id == '+ model_name +' & activity_id==\"CMIP\" & table_id == \"Omon\" & variable_id == \"thetao\" & experiment_id == '+experiment\n",
    "\n",
    " #   theta = df.query('source_id =='+ model_name +' & table_id == \"Amon\" & variable_id == \"ts\" & experiment_id =='+ experiment+'& member_id == \"r1i1p1f1\"')\n",
    " #   tauu=df.query('source_id =='+ model_name +'& table_id == \"Amon\" & variable_id == \"tauu\" & experiment_id =='+ experiment+'& member_id == \"r1i1p1f1\"')\n",
    "    theta = df.query('source_id =='+ model_name +' & table_id == \"Amon\" & variable_id == \"ts\" & experiment_id =='+ experiment)\n",
    "   # tauu=df.query('source_id =='+ model_name +'& table_id == \"Amon\" & variable_id == \"tauu\" & experiment_id =='+ experiment)\n",
    "\n",
    "    import xesmf as xe # I use xesmf to regrid from the ocean curvelinear to lat/lon grid\n",
    "\n",
    "    theta_pi=get_df(theta)\n",
    "    theta_trop=theta_pi.sel(lon=slice(140,280)).sel(lat=slice(-15,15)).isel(time=slice(0,200*12))\n",
    "    sst_low=theta_trop['ts'].assign_coords(time=range(0,len(theta_trop.time)))\n",
    "    sst_low.load()\n",
    "    sst_low= dsp.bandpass(sst_low,1/(10*12),1/(1.5*12),dim='time')\n",
    "\n",
    "    sst_low=sst_low.transpose(\"time\", \"lon\", \"lat\")\n",
    "\n",
    "    solver = Eof(sst_low)\n",
    "\n",
    "    eofs = solver.eofs(neofs=2)\n",
    "    pcs = solver.pcs(npcs=2)\n",
    "    pcs = (pcs-pcs.mean('time'))/pcs.std('time')\n",
    "    eofs=eofs.transpose(\"lat\", \"lon\",'mode')\n",
    "    \n",
    "    model_name='\"'+model_names[x]+'\"'\n",
    "    experiment='\"ssp585\"'\n",
    "    \n",
    "    def get_df(invar):\n",
    "# this only needs to be created once\n",
    "        gcs = gcsfs.GCSFileSystem(token='anon')\n",
    "\n",
    "# get the path to a specific zarr store (the first one from the dataframe above)\n",
    "        zstore = invar.zstore.values[1]\n",
    "\n",
    "# create a mutable-mapping-style interface to the store\n",
    "        mapper = gcs.get_mapper(zstore)\n",
    "\n",
    "# open it using xarray and zarr\n",
    "        outvar = xr.open_zarr(mapper, consolidated=True)\n",
    "\n",
    "        return outvar\n",
    "\n",
    "    test='source_id == '+ model_name +' & activity_id==\"CMIP\" & table_id == \"Omon\" & variable_id == \"thetao\" & experiment_id == '+experiment\n",
    "\n",
    " #   theta = df.query('source_id =='+ model_name +' & table_id == \"Amon\" & variable_id == \"ts\" & experiment_id =='+ experiment+'& member_id == \"r1i1p1f1\"')\n",
    " #   tauu=df.query('source_id =='+ model_name +'& table_id == \"Amon\" & variable_id == \"tauu\" & experiment_id =='+ experiment+'& member_id == \"r1i1p1f1\"')\n",
    "    theta = df.query('source_id =='+ model_name +' & table_id == \"Amon\" & variable_id == \"ts\" & experiment_id =='+ experiment)\n",
    "   # tauu=df.query('source_id =='+ model_name +'& table_id == \"Amon\" & variable_id == \"tauu\" & experiment_id =='+ experiment)\n",
    "\n",
    "    import xesmf as xe # I use xesmf to regrid from the ocean curvelinear to lat/lon grid\n",
    "\n",
    "    theta_pi=get_df(theta)\n",
    "    theta_trop=theta_pi.sel(lon=slice(140,280)).sel(lat=slice(-15,15))\n",
    "    sst_low=theta_trop['ts'].assign_coords(time=range(0,len(theta_trop.time)))\n",
    "    sst_low.load()\n",
    "    sst_low= dsp.bandpass(sst_low,1/(10*12),1/(1.5*12),dim='time')\n",
    "\n",
    "    sst_low=sst_low.transpose(\"time\", \"lon\", \"lat\")\n",
    "\n",
    "    pseudo_pcs = solver.projectField(sst_low, neofs=2)\n",
    "\n",
    "\n",
    "    E_index=(pseudo_pcs.sel(mode=0)+pseudo_pcs.sel(mode=1))#**(-1/2)\n",
    "    E_index=E_index/math.sqrt(2)\n",
    "\n",
    "    E_index.to_netcdf('C_index_proj'+model_names[x]+'_ssp585_2.nc')\n",
    "  "
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "id": "d78bfa90-4f25-4e4f-bf74-75885b84abc3",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "/srv/conda/envs/notebook/lib/python3.10/site-packages/xarray/coding/times.py:699: SerializationWarning: Unable to decode time axis into full numpy.datetime64 objects, continuing using cftime.datetime objects instead, reason: dates out of range\n",
      "  dtype = _decode_cf_datetime_dtype(data, units, calendar, self.use_cftime)\n",
      "/srv/conda/envs/notebook/lib/python3.10/site-packages/xarray/coding/times.py:150: SerializationWarning: Ambiguous reference date string: 950-01-01. The first value is assumed to be the year hence will be padded with zeros to remove the ambiguity (the padded reference date string is: 0950-01-01). To remove this message, remove the ambiguity by padding your reference date strings with zeros.\n",
      "  warnings.warn(warning_msg, SerializationWarning)\n",
      "/srv/conda/envs/notebook/lib/python3.10/site-packages/xarray/core/indexing.py:524: SerializationWarning: Unable to decode time axis into full numpy.datetime64 objects, continuing using cftime.datetime objects instead, reason: dates out of range\n",
      "  return np.asarray(array[self.key], dtype=None)\n",
      "/srv/conda/envs/notebook/lib/python3.10/site-packages/xarray/coding/times.py:699: SerializationWarning: Unable to decode time axis into full numpy.datetime64 objects, continuing using cftime.datetime objects instead, reason: dates out of range\n",
      "  dtype = _decode_cf_datetime_dtype(data, units, calendar, self.use_cftime)\n",
      "/srv/conda/envs/notebook/lib/python3.10/site-packages/xarray/coding/times.py:699: SerializationWarning: Unable to decode time axis into full numpy.datetime64 objects, continuing using cftime.datetime objects instead, reason: dates out of range\n",
      "  dtype = _decode_cf_datetime_dtype(data, units, calendar, self.use_cftime)\n",
      "/srv/conda/envs/notebook/lib/python3.10/site-packages/xarray/core/indexing.py:524: SerializationWarning: Unable to decode time axis into full numpy.datetime64 objects, continuing using cftime.datetime objects instead, reason: dates out of range\n",
      "  return np.asarray(array[self.key], dtype=None)\n",
      "/srv/conda/envs/notebook/lib/python3.10/site-packages/xarray/coding/times.py:699: SerializationWarning: Unable to decode time axis into full numpy.datetime64 objects, continuing using cftime.datetime objects instead, reason: dates out of range\n",
      "  dtype = _decode_cf_datetime_dtype(data, units, calendar, self.use_cftime)\n",
      "/srv/conda/envs/notebook/lib/python3.10/site-packages/xarray/core/indexing.py:524: SerializationWarning: Unable to decode time axis into full numpy.datetime64 objects, continuing using cftime.datetime objects instead, reason: dates out of range\n",
      "  return np.asarray(array[self.key], dtype=None)\n",
      "/srv/conda/envs/notebook/lib/python3.10/site-packages/xarray/coding/times.py:699: SerializationWarning: Unable to decode time axis into full numpy.datetime64 objects, continuing using cftime.datetime objects instead, reason: dates out of range\n",
      "  dtype = _decode_cf_datetime_dtype(data, units, calendar, self.use_cftime)\n",
      "/srv/conda/envs/notebook/lib/python3.10/site-packages/xarray/coding/times.py:699: SerializationWarning: Unable to decode time axis into full numpy.datetime64 objects, continuing using cftime.datetime objects instead, reason: dates out of range\n",
      "  dtype = _decode_cf_datetime_dtype(data, units, calendar, self.use_cftime)\n",
      "/srv/conda/envs/notebook/lib/python3.10/site-packages/xarray/core/indexing.py:524: SerializationWarning: Unable to decode time axis into full numpy.datetime64 objects, continuing using cftime.datetime objects instead, reason: dates out of range\n",
      "  return np.asarray(array[self.key], dtype=None)\n",
      "/srv/conda/envs/notebook/lib/python3.10/site-packages/xarray/coding/times.py:699: SerializationWarning: Unable to decode time axis into full numpy.datetime64 objects, continuing using cftime.datetime objects instead, reason: dates out of range\n",
      "  dtype = _decode_cf_datetime_dtype(data, units, calendar, self.use_cftime)\n",
      "/srv/conda/envs/notebook/lib/python3.10/site-packages/xarray/core/indexing.py:524: SerializationWarning: Unable to decode time axis into full numpy.datetime64 objects, continuing using cftime.datetime objects instead, reason: dates out of range\n",
      "  return np.asarray(array[self.key], dtype=None)\n",
      "/srv/conda/envs/notebook/lib/python3.10/site-packages/xarray/coding/times.py:699: SerializationWarning: Unable to decode time axis into full numpy.datetime64 objects, continuing using cftime.datetime objects instead, reason: dates out of range\n",
      "  dtype = _decode_cf_datetime_dtype(data, units, calendar, self.use_cftime)\n",
      "/srv/conda/envs/notebook/lib/python3.10/site-packages/xarray/coding/times.py:699: SerializationWarning: Unable to decode time axis into full numpy.datetime64 objects, continuing using cftime.datetime objects instead, reason: dates out of range\n",
      "  dtype = _decode_cf_datetime_dtype(data, units, calendar, self.use_cftime)\n",
      "/srv/conda/envs/notebook/lib/python3.10/site-packages/xarray/core/indexing.py:524: SerializationWarning: Unable to decode time axis into full numpy.datetime64 objects, continuing using cftime.datetime objects instead, reason: dates out of range\n",
      "  return np.asarray(array[self.key], dtype=None)\n",
      "/srv/conda/envs/notebook/lib/python3.10/site-packages/xarray/coding/times.py:699: SerializationWarning: Unable to decode time axis into full numpy.datetime64 objects, continuing using cftime.datetime objects instead, reason: dates out of range\n",
      "  dtype = _decode_cf_datetime_dtype(data, units, calendar, self.use_cftime)\n",
      "/srv/conda/envs/notebook/lib/python3.10/site-packages/xarray/coding/times.py:699: SerializationWarning: Unable to decode time axis into full numpy.datetime64 objects, continuing using cftime.datetime objects instead, reason: dates out of range\n",
      "  dtype = _decode_cf_datetime_dtype(data, units, calendar, self.use_cftime)\n",
      "/srv/conda/envs/notebook/lib/python3.10/site-packages/xarray/core/indexing.py:524: SerializationWarning: Unable to decode time axis into full numpy.datetime64 objects, continuing using cftime.datetime objects instead, reason: dates out of range\n",
      "  return np.asarray(array[self.key], dtype=None)\n",
      "/srv/conda/envs/notebook/lib/python3.10/site-packages/xarray/coding/times.py:699: SerializationWarning: Unable to decode time axis into full numpy.datetime64 objects, continuing using cftime.datetime objects instead, reason: dates out of range\n",
      "  dtype = _decode_cf_datetime_dtype(data, units, calendar, self.use_cftime)\n",
      "/srv/conda/envs/notebook/lib/python3.10/site-packages/xarray/core/indexing.py:524: SerializationWarning: Unable to decode time axis into full numpy.datetime64 objects, continuing using cftime.datetime objects instead, reason: dates out of range\n",
      "  return np.asarray(array[self.key], dtype=None)\n",
      "/srv/conda/envs/notebook/lib/python3.10/site-packages/xarray/coding/times.py:699: SerializationWarning: Unable to decode time axis into full numpy.datetime64 objects, continuing using cftime.datetime objects instead, reason: dates out of range\n",
      "  dtype = _decode_cf_datetime_dtype(data, units, calendar, self.use_cftime)\n",
      "/srv/conda/envs/notebook/lib/python3.10/site-packages/xarray/coding/times.py:699: SerializationWarning: Unable to decode time axis into full numpy.datetime64 objects, continuing using cftime.datetime objects instead, reason: dates out of range\n",
      "  dtype = _decode_cf_datetime_dtype(data, units, calendar, self.use_cftime)\n",
      "/srv/conda/envs/notebook/lib/python3.10/site-packages/xarray/core/indexing.py:524: SerializationWarning: Unable to decode time axis into full numpy.datetime64 objects, continuing using cftime.datetime objects instead, reason: dates out of range\n",
      "  return np.asarray(array[self.key], dtype=None)\n",
      "/srv/conda/envs/notebook/lib/python3.10/site-packages/xarray/coding/times.py:699: SerializationWarning: Unable to decode time axis into full numpy.datetime64 objects, continuing using cftime.datetime objects instead, reason: dates out of range\n",
      "  dtype = _decode_cf_datetime_dtype(data, units, calendar, self.use_cftime)\n",
      "/srv/conda/envs/notebook/lib/python3.10/site-packages/xarray/coding/times.py:699: SerializationWarning: Unable to decode time axis into full numpy.datetime64 objects, continuing using cftime.datetime objects instead, reason: dates out of range\n",
      "  dtype = _decode_cf_datetime_dtype(data, units, calendar, self.use_cftime)\n",
      "/srv/conda/envs/notebook/lib/python3.10/site-packages/xarray/core/indexing.py:524: SerializationWarning: Unable to decode time axis into full numpy.datetime64 objects, continuing using cftime.datetime objects instead, reason: dates out of range\n",
      "  return np.asarray(array[self.key], dtype=None)\n"
     ]
    }
   ],
   "source": [
    "df = pd.read_csv('https://storage.googleapis.com/cmip6/cmip6-zarr-consolidated-stores.csv')\n",
    "df.head()\n",
    "\n",
    "\n",
    "\n",
    "model_names=['ACCESS-CM2','ACCESS-ESM1-5','CanESM5-CanOE','CanESM5','CESM2-WACCM','CESM2',\\\n",
    "             'CNRM-CM6-1','CNRM-ESM2-1','EC-Earth3','EC-Earth3-Veg','FGOALS-g3',\\\n",
    "                 'FIO-ESM-2-0','HadGEM3-GC31-LL','HadGEM3-GC31-MM','IPSL-CM6A-LR','KACE-1-0-G',\\\n",
    "                    'MIROC6','MIROC-ES2L', 'MPI-ESM1-2-LR','UKESM1-0-LL']\n",
    "\n",
    "for x in range(0,len(model_names)):\n",
    "\n",
    "    def get_df(invar):\n",
    "# this only needs to be created once\n",
    "        gcs = gcsfs.GCSFileSystem(token='anon')\n",
    "\n",
    "# get the path to a specific zarr store (the first one from the dataframe above)\n",
    "        zstore = invar.zstore.values[0]\n",
    "\n",
    "# create a mutable-mapping-style interface to the store\n",
    "        mapper = gcs.get_mapper(zstore)\n",
    "\n",
    "# open it using xarray and zarr\n",
    "        outvar = xr.open_zarr(mapper, consolidated=True)\n",
    "\n",
    "        return outvar\n",
    "    \n",
    "    model_name='\"'+model_names[x]+'\"'\n",
    "    experiment='\"piControl\"'\n",
    "\n",
    "    test='source_id == '+ model_name +' & activity_id==\"CMIP\" & table_id == \"Omon\" & variable_id == \"thetao\" & experiment_id == '+experiment\n",
    "\n",
    " #   theta = df.query('source_id =='+ model_name +' & table_id == \"Amon\" & variable_id == \"ts\" & experiment_id =='+ experiment+'& member_id == \"r1i1p1f1\"')\n",
    " #   tauu=df.query('source_id =='+ model_name +'& table_id == \"Amon\" & variable_id == \"tauu\" & experiment_id =='+ experiment+'& member_id == \"r1i1p1f1\"')\n",
    "    theta = df.query('source_id =='+ model_name +' & table_id == \"Amon\" & variable_id == \"ts\" & experiment_id =='+ experiment)\n",
    "   # tauu=df.query('source_id =='+ model_name +'& table_id == \"Amon\" & variable_id == \"tauu\" & experiment_id =='+ experiment)\n",
    "\n",
    "    import xesmf as xe # I use xesmf to regrid from the ocean curvelinear to lat/lon grid\n",
    "\n",
    "    theta_pi=get_df(theta)\n",
    "    theta_trop=theta_pi.sel(lon=slice(140,280)).sel(lat=slice(-15,15)).isel(time=slice(0,200*12))\n",
    "    sst_low=theta_trop['ts'].assign_coords(time=range(0,len(theta_trop.time)))\n",
    "    sst_low.load()\n",
    "    sst_low= dsp.bandpass(sst_low,1/(10*12),1/(1.5*12),dim='time')\n",
    "\n",
    "    sst_low=sst_low.transpose(\"time\", \"lon\", \"lat\")\n",
    "\n",
    "    solver = Eof(sst_low)\n",
    "\n",
    "    eofs = solver.eofs(neofs=2)\n",
    "    pcs = solver.pcs(npcs=2)\n",
    "    pcs = (pcs-pcs.mean('time'))/pcs.std('time')    \n",
    "    eofs=eofs.transpose(\"lat\", \"lon\",'mode')\n",
    "    \n",
    "    model_name='\"'+model_names[x]+'\"'\n",
    "    experiment='\"ssp585\"'\n",
    "    \n",
    "    def get_df(invar):\n",
    "# this only needs to be created once\n",
    "        gcs = gcsfs.GCSFileSystem(token='anon')\n",
    "\n",
    "# get the path to a specific zarr store (the first one from the dataframe above)\n",
    "        zstore = invar.zstore.values[2]\n",
    "\n",
    "# create a mutable-mapping-style interface to the store\n",
    "        mapper = gcs.get_mapper(zstore)\n",
    "\n",
    "# open it using xarray and zarr\n",
    "        outvar = xr.open_zarr(mapper, consolidated=True)\n",
    "\n",
    "        return outvar\n",
    "\n",
    "    test='source_id == '+ model_name +' & activity_id==\"CMIP\" & table_id == \"Omon\" & variable_id == \"thetao\" & experiment_id == '+experiment\n",
    "\n",
    " #   theta = df.query('source_id =='+ model_name +' & table_id == \"Amon\" & variable_id == \"ts\" & experiment_id =='+ experiment+'& member_id == \"r1i1p1f1\"')\n",
    " #   tauu=df.query('source_id =='+ model_name +'& table_id == \"Amon\" & variable_id == \"tauu\" & experiment_id =='+ experiment+'& member_id == \"r1i1p1f1\"')\n",
    "    theta = df.query('source_id =='+ model_name +' & table_id == \"Amon\" & variable_id == \"ts\" & experiment_id =='+ experiment)\n",
    "   # tauu=df.query('source_id =='+ model_name +'& table_id == \"Amon\" & variable_id == \"tauu\" & experiment_id =='+ experiment)\n",
    "\n",
    "    import xesmf as xe # I use xesmf to regrid from the ocean curvelinear to lat/lon grid\n",
    "\n",
    "    theta_pi=get_df(theta)\n",
    "    theta_trop=theta_pi.sel(lon=slice(140,280)).sel(lat=slice(-15,15))\n",
    "    sst_low=theta_trop['ts'].assign_coords(time=range(0,len(theta_trop.time)))\n",
    "    sst_low.load()\n",
    "    sst_low= dsp.bandpass(sst_low,1/(10*12),1/(1.5*12),dim='time')\n",
    "\n",
    "    sst_low=sst_low.transpose(\"time\", \"lon\", \"lat\")\n",
    "\n",
    "    pseudo_pcs = solver.projectField(sst_low, neofs=2)\n",
    "\n",
    "\n",
    "    E_index=(pseudo_pcs.sel(mode=0)+pseudo_pcs.sel(mode=1))#**(-1/2)\n",
    "    E_index=E_index/math.sqrt(2)\n",
    "\n",
    "    E_index.to_netcdf('C_index_proj'+model_names[x]+'_ssp585_3.nc')\n",
    "  "
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "id": "2061f78a-bb99-42b5-819c-7122628e8b49",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "/srv/conda/envs/notebook/lib/python3.10/site-packages/xarray/coding/times.py:699: SerializationWarning: Unable to decode time axis into full numpy.datetime64 objects, continuing using cftime.datetime objects instead, reason: dates out of range\n",
      "  dtype = _decode_cf_datetime_dtype(data, units, calendar, self.use_cftime)\n",
      "/srv/conda/envs/notebook/lib/python3.10/site-packages/xarray/coding/times.py:150: SerializationWarning: Ambiguous reference date string: 950-01-01. The first value is assumed to be the year hence will be padded with zeros to remove the ambiguity (the padded reference date string is: 0950-01-01). To remove this message, remove the ambiguity by padding your reference date strings with zeros.\n",
      "  warnings.warn(warning_msg, SerializationWarning)\n",
      "/srv/conda/envs/notebook/lib/python3.10/site-packages/xarray/core/indexing.py:524: SerializationWarning: Unable to decode time axis into full numpy.datetime64 objects, continuing using cftime.datetime objects instead, reason: dates out of range\n",
      "  return np.asarray(array[self.key], dtype=None)\n",
      "/srv/conda/envs/notebook/lib/python3.10/site-packages/xarray/coding/times.py:699: SerializationWarning: Unable to decode time axis into full numpy.datetime64 objects, continuing using cftime.datetime objects instead, reason: dates out of range\n",
      "  dtype = _decode_cf_datetime_dtype(data, units, calendar, self.use_cftime)\n",
      "/srv/conda/envs/notebook/lib/python3.10/site-packages/xarray/core/indexing.py:524: SerializationWarning: Unable to decode time axis into full numpy.datetime64 objects, continuing using cftime.datetime objects instead, reason: dates out of range\n",
      "  return np.asarray(array[self.key], dtype=None)\n",
      "/srv/conda/envs/notebook/lib/python3.10/site-packages/xarray/coding/times.py:699: SerializationWarning: Unable to decode time axis into full numpy.datetime64 objects, continuing using cftime.datetime objects instead, reason: dates out of range\n",
      "  dtype = _decode_cf_datetime_dtype(data, units, calendar, self.use_cftime)\n",
      "/srv/conda/envs/notebook/lib/python3.10/site-packages/xarray/core/indexing.py:524: SerializationWarning: Unable to decode time axis into full numpy.datetime64 objects, continuing using cftime.datetime objects instead, reason: dates out of range\n",
      "  return np.asarray(array[self.key], dtype=None)\n",
      "/srv/conda/envs/notebook/lib/python3.10/site-packages/xarray/coding/times.py:699: SerializationWarning: Unable to decode time axis into full numpy.datetime64 objects, continuing using cftime.datetime objects instead, reason: dates out of range\n",
      "  dtype = _decode_cf_datetime_dtype(data, units, calendar, self.use_cftime)\n",
      "/srv/conda/envs/notebook/lib/python3.10/site-packages/xarray/coding/times.py:699: SerializationWarning: Unable to decode time axis into full numpy.datetime64 objects, continuing using cftime.datetime objects instead, reason: dates out of range\n",
      "  dtype = _decode_cf_datetime_dtype(data, units, calendar, self.use_cftime)\n",
      "/srv/conda/envs/notebook/lib/python3.10/site-packages/xarray/core/indexing.py:524: SerializationWarning: Unable to decode time axis into full numpy.datetime64 objects, continuing using cftime.datetime objects instead, reason: dates out of range\n",
      "  return np.asarray(array[self.key], dtype=None)\n",
      "/srv/conda/envs/notebook/lib/python3.10/site-packages/xarray/coding/times.py:699: SerializationWarning: Unable to decode time axis into full numpy.datetime64 objects, continuing using cftime.datetime objects instead, reason: dates out of range\n",
      "  dtype = _decode_cf_datetime_dtype(data, units, calendar, self.use_cftime)\n",
      "/srv/conda/envs/notebook/lib/python3.10/site-packages/xarray/coding/times.py:699: SerializationWarning: Unable to decode time axis into full numpy.datetime64 objects, continuing using cftime.datetime objects instead, reason: dates out of range\n",
      "  dtype = _decode_cf_datetime_dtype(data, units, calendar, self.use_cftime)\n",
      "/srv/conda/envs/notebook/lib/python3.10/site-packages/xarray/core/indexing.py:524: SerializationWarning: Unable to decode time axis into full numpy.datetime64 objects, continuing using cftime.datetime objects instead, reason: dates out of range\n",
      "  return np.asarray(array[self.key], dtype=None)\n",
      "/srv/conda/envs/notebook/lib/python3.10/site-packages/xarray/coding/times.py:699: SerializationWarning: Unable to decode time axis into full numpy.datetime64 objects, continuing using cftime.datetime objects instead, reason: dates out of range\n",
      "  dtype = _decode_cf_datetime_dtype(data, units, calendar, self.use_cftime)\n",
      "/srv/conda/envs/notebook/lib/python3.10/site-packages/xarray/core/indexing.py:524: SerializationWarning: Unable to decode time axis into full numpy.datetime64 objects, continuing using cftime.datetime objects instead, reason: dates out of range\n",
      "  return np.asarray(array[self.key], dtype=None)\n",
      "/srv/conda/envs/notebook/lib/python3.10/site-packages/xarray/coding/times.py:699: SerializationWarning: Unable to decode time axis into full numpy.datetime64 objects, continuing using cftime.datetime objects instead, reason: dates out of range\n",
      "  dtype = _decode_cf_datetime_dtype(data, units, calendar, self.use_cftime)\n",
      "/srv/conda/envs/notebook/lib/python3.10/site-packages/xarray/coding/times.py:699: SerializationWarning: Unable to decode time axis into full numpy.datetime64 objects, continuing using cftime.datetime objects instead, reason: dates out of range\n",
      "  dtype = _decode_cf_datetime_dtype(data, units, calendar, self.use_cftime)\n",
      "/srv/conda/envs/notebook/lib/python3.10/site-packages/xarray/core/indexing.py:524: SerializationWarning: Unable to decode time axis into full numpy.datetime64 objects, continuing using cftime.datetime objects instead, reason: dates out of range\n",
      "  return np.asarray(array[self.key], dtype=None)\n",
      "/srv/conda/envs/notebook/lib/python3.10/site-packages/xarray/coding/times.py:699: SerializationWarning: Unable to decode time axis into full numpy.datetime64 objects, continuing using cftime.datetime objects instead, reason: dates out of range\n",
      "  dtype = _decode_cf_datetime_dtype(data, units, calendar, self.use_cftime)\n",
      "/srv/conda/envs/notebook/lib/python3.10/site-packages/xarray/coding/times.py:699: SerializationWarning: Unable to decode time axis into full numpy.datetime64 objects, continuing using cftime.datetime objects instead, reason: dates out of range\n",
      "  dtype = _decode_cf_datetime_dtype(data, units, calendar, self.use_cftime)\n",
      "/srv/conda/envs/notebook/lib/python3.10/site-packages/xarray/core/indexing.py:524: SerializationWarning: Unable to decode time axis into full numpy.datetime64 objects, continuing using cftime.datetime objects instead, reason: dates out of range\n",
      "  return np.asarray(array[self.key], dtype=None)\n"
     ]
    }
   ],
   "source": [
    "df = pd.read_csv('https://storage.googleapis.com/cmip6/cmip6-zarr-consolidated-stores.csv')\n",
    "df.head()\n",
    "\n",
    "def get_df(invar):\n",
    "# this only needs to be created once\n",
    "    gcs = gcsfs.GCSFileSystem(token='anon')\n",
    "\n",
    "# get the path to a specific zarr store (the first one from the dataframe above)\n",
    "    zstore = invar.zstore.values[0]\n",
    "\n",
    "# create a mutable-mapping-style interface to the store\n",
    "    mapper = gcs.get_mapper(zstore)\n",
    "\n",
    "# open it using xarray and zarr\n",
    "    outvar = xr.open_zarr(mapper, consolidated=True)\n",
    "\n",
    "    return outvar\n",
    "\n",
    "model_names=['ACCESS-CM2','ACCESS-ESM1-5','CanESM5-CanOE','CanESM5','CESM2-WACCM','CESM2',\\\n",
    "             'CNRM-CM6-1','CNRM-ESM2-1','EC-Earth3','EC-Earth3-Veg','FGOALS-g3',\\\n",
    "                 'FIO-ESM-2-0','HadGEM3-GC31-LL','HadGEM3-GC31-MM','IPSL-CM6A-LR','KACE-1-0-G',\\\n",
    "                    'MIROC6','MIROC-ES2L', 'MPI-ESM1-2-LR','UKESM1-0-LL']\n",
    "\n",
    "for x in range(0,len(model_names)):\n",
    "\n",
    "    \n",
    "    model_name='\"'+model_names[x]+'\"'\n",
    "    experiment='\"piControl\"'\n",
    "\n",
    "    test='source_id == '+ model_name +' & activity_id==\"CMIP\" & table_id == \"Omon\" & variable_id == \"thetao\" & experiment_id == '+experiment\n",
    "\n",
    " #   theta = df.query('source_id =='+ model_name +' & table_id == \"Amon\" & variable_id == \"ts\" & experiment_id =='+ experiment+'& member_id == \"r1i1p1f1\"')\n",
    " #   tauu=df.query('source_id =='+ model_name +'& table_id == \"Amon\" & variable_id == \"tauu\" & experiment_id =='+ experiment+'& member_id == \"r1i1p1f1\"')\n",
    "    theta = df.query('source_id =='+ model_name +' & table_id == \"Amon\" & variable_id == \"ts\" & experiment_id =='+ experiment)\n",
    "   # tauu=df.query('source_id =='+ model_name +'& table_id == \"Amon\" & variable_id == \"tauu\" & experiment_id =='+ experiment)\n",
    "\n",
    "    import xesmf as xe # I use xesmf to regrid from the ocean curvelinear to lat/lon grid\n",
    "\n",
    "\n",
    "    theta_pi=get_df(theta)\n",
    "    theta_trop=theta_pi.sel(lon=slice(140,280)).sel(lat=slice(-15,15)).isel(time=slice(0,200*12))\n",
    "    sst_low=theta_trop['ts'].assign_coords(time=range(0,len(theta_trop.time)))\n",
    "    sst_low.load()\n",
    "    sst_low= dsp.bandpass(sst_low,1/(10*12),1/(1.5*12),dim='time')\n",
    "\n",
    "    sst_low=sst_low.transpose(\"time\", \"lon\", \"lat\")\n",
    "\n",
    "    solver = Eof(sst_low)\n",
    "\n",
    "    eofs = solver.eofs(neofs=2)\n",
    "    pcs = (pcs-pcs.mean('time'))/pcs.std('time')    \n",
    "    pcs = solver.pcs(npcs=2)\n",
    "    eofs=eofs.transpose(\"lat\", \"lon\",'mode')\n",
    "\n",
    "    E_index=(pcs.sel(mode=0)+pcs.sel(mode=1))#**(-1/2)\n",
    "    E_index=E_index/math.sqrt(2)\n",
    "\n",
    "    E_index.to_netcdf('C_index'+model_names[x]+'_piControl.nc')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 7,
   "id": "5e99cf71-246e-47ec-82e5-376c2da223ca",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "/srv/conda/envs/notebook/lib/python3.10/site-packages/xarray/coding/times.py:699: SerializationWarning: Unable to decode time axis into full numpy.datetime64 objects, continuing using cftime.datetime objects instead, reason: dates out of range\n",
      "  dtype = _decode_cf_datetime_dtype(data, units, calendar, self.use_cftime)\n",
      "/srv/conda/envs/notebook/lib/python3.10/site-packages/xarray/coding/times.py:150: SerializationWarning: Ambiguous reference date string: 950-01-01. The first value is assumed to be the year hence will be padded with zeros to remove the ambiguity (the padded reference date string is: 0950-01-01). To remove this message, remove the ambiguity by padding your reference date strings with zeros.\n",
      "  warnings.warn(warning_msg, SerializationWarning)\n",
      "/srv/conda/envs/notebook/lib/python3.10/site-packages/xarray/core/indexing.py:524: SerializationWarning: Unable to decode time axis into full numpy.datetime64 objects, continuing using cftime.datetime objects instead, reason: dates out of range\n",
      "  return np.asarray(array[self.key], dtype=None)\n",
      "/srv/conda/envs/notebook/lib/python3.10/site-packages/xarray/coding/times.py:699: SerializationWarning: Unable to decode time axis into full numpy.datetime64 objects, continuing using cftime.datetime objects instead, reason: dates out of range\n",
      "  dtype = _decode_cf_datetime_dtype(data, units, calendar, self.use_cftime)\n",
      "/srv/conda/envs/notebook/lib/python3.10/site-packages/xarray/coding/times.py:150: SerializationWarning: Ambiguous reference date string: 950-01-01. The first value is assumed to be the year hence will be padded with zeros to remove the ambiguity (the padded reference date string is: 0950-01-01). To remove this message, remove the ambiguity by padding your reference date strings with zeros.\n",
      "  warnings.warn(warning_msg, SerializationWarning)\n",
      "/srv/conda/envs/notebook/lib/python3.10/site-packages/xarray/core/indexing.py:524: SerializationWarning: Unable to decode time axis into full numpy.datetime64 objects, continuing using cftime.datetime objects instead, reason: dates out of range\n",
      "  return np.asarray(array[self.key], dtype=None)\n",
      "/srv/conda/envs/notebook/lib/python3.10/site-packages/xarray/coding/times.py:699: SerializationWarning: Unable to decode time axis into full numpy.datetime64 objects, continuing using cftime.datetime objects instead, reason: dates out of range\n",
      "  dtype = _decode_cf_datetime_dtype(data, units, calendar, self.use_cftime)\n",
      "/srv/conda/envs/notebook/lib/python3.10/site-packages/xarray/core/indexing.py:524: SerializationWarning: Unable to decode time axis into full numpy.datetime64 objects, continuing using cftime.datetime objects instead, reason: dates out of range\n",
      "  return np.asarray(array[self.key], dtype=None)\n",
      "/srv/conda/envs/notebook/lib/python3.10/site-packages/xarray/coding/times.py:699: SerializationWarning: Unable to decode time axis into full numpy.datetime64 objects, continuing using cftime.datetime objects instead, reason: dates out of range\n",
      "  dtype = _decode_cf_datetime_dtype(data, units, calendar, self.use_cftime)\n",
      "/srv/conda/envs/notebook/lib/python3.10/site-packages/xarray/coding/times.py:150: SerializationWarning: Ambiguous reference date string: 101-01-01. The first value is assumed to be the year hence will be padded with zeros to remove the ambiguity (the padded reference date string is: 0101-01-01). To remove this message, remove the ambiguity by padding your reference date strings with zeros.\n",
      "  warnings.warn(warning_msg, SerializationWarning)\n",
      "/srv/conda/envs/notebook/lib/python3.10/site-packages/xarray/core/indexing.py:524: SerializationWarning: Unable to decode time axis into full numpy.datetime64 objects, continuing using cftime.datetime objects instead, reason: dates out of range\n",
      "  return np.asarray(array[self.key], dtype=None)\n",
      "/srv/conda/envs/notebook/lib/python3.10/site-packages/xarray/coding/times.py:699: SerializationWarning: Unable to decode time axis into full numpy.datetime64 objects, continuing using cftime.datetime objects instead, reason: dates out of range\n",
      "  dtype = _decode_cf_datetime_dtype(data, units, calendar, self.use_cftime)\n",
      "/srv/conda/envs/notebook/lib/python3.10/site-packages/xarray/core/indexing.py:524: SerializationWarning: Unable to decode time axis into full numpy.datetime64 objects, continuing using cftime.datetime objects instead, reason: dates out of range\n",
      "  return np.asarray(array[self.key], dtype=None)\n",
      "/srv/conda/envs/notebook/lib/python3.10/site-packages/xarray/coding/times.py:699: SerializationWarning: Unable to decode time axis into full numpy.datetime64 objects, continuing using cftime.datetime objects instead, reason: dates out of range\n",
      "  dtype = _decode_cf_datetime_dtype(data, units, calendar, self.use_cftime)\n",
      "/srv/conda/envs/notebook/lib/python3.10/site-packages/xarray/coding/times.py:699: SerializationWarning: Unable to decode time axis into full numpy.datetime64 objects, continuing using cftime.datetime objects instead, reason: dates out of range\n",
      "  dtype = _decode_cf_datetime_dtype(data, units, calendar, self.use_cftime)\n",
      "/srv/conda/envs/notebook/lib/python3.10/site-packages/xarray/core/indexing.py:524: SerializationWarning: Unable to decode time axis into full numpy.datetime64 objects, continuing using cftime.datetime objects instead, reason: dates out of range\n",
      "  return np.asarray(array[self.key], dtype=None)\n",
      "/srv/conda/envs/notebook/lib/python3.10/site-packages/xarray/coding/times.py:699: SerializationWarning: Unable to decode time axis into full numpy.datetime64 objects, continuing using cftime.datetime objects instead, reason: dates out of range\n",
      "  dtype = _decode_cf_datetime_dtype(data, units, calendar, self.use_cftime)\n",
      "/srv/conda/envs/notebook/lib/python3.10/site-packages/xarray/coding/times.py:699: SerializationWarning: Unable to decode time axis into full numpy.datetime64 objects, continuing using cftime.datetime objects instead, reason: dates out of range\n",
      "  dtype = _decode_cf_datetime_dtype(data, units, calendar, self.use_cftime)\n",
      "/srv/conda/envs/notebook/lib/python3.10/site-packages/xarray/core/indexing.py:524: SerializationWarning: Unable to decode time axis into full numpy.datetime64 objects, continuing using cftime.datetime objects instead, reason: dates out of range\n",
      "  return np.asarray(array[self.key], dtype=None)\n",
      "/srv/conda/envs/notebook/lib/python3.10/site-packages/xarray/coding/times.py:699: SerializationWarning: Unable to decode time axis into full numpy.datetime64 objects, continuing using cftime.datetime objects instead, reason: dates out of range\n",
      "  dtype = _decode_cf_datetime_dtype(data, units, calendar, self.use_cftime)\n",
      "/srv/conda/envs/notebook/lib/python3.10/site-packages/xarray/core/indexing.py:524: SerializationWarning: Unable to decode time axis into full numpy.datetime64 objects, continuing using cftime.datetime objects instead, reason: dates out of range\n",
      "  return np.asarray(array[self.key], dtype=None)\n",
      "/srv/conda/envs/notebook/lib/python3.10/site-packages/xarray/coding/times.py:699: SerializationWarning: Unable to decode time axis into full numpy.datetime64 objects, continuing using cftime.datetime objects instead, reason: dates out of range\n",
      "  dtype = _decode_cf_datetime_dtype(data, units, calendar, self.use_cftime)\n",
      "/srv/conda/envs/notebook/lib/python3.10/site-packages/xarray/core/indexing.py:524: SerializationWarning: Unable to decode time axis into full numpy.datetime64 objects, continuing using cftime.datetime objects instead, reason: dates out of range\n",
      "  return np.asarray(array[self.key], dtype=None)\n",
      "/srv/conda/envs/notebook/lib/python3.10/site-packages/xarray/coding/times.py:699: SerializationWarning: Unable to decode time axis into full numpy.datetime64 objects, continuing using cftime.datetime objects instead, reason: dates out of range\n",
      "  dtype = _decode_cf_datetime_dtype(data, units, calendar, self.use_cftime)\n",
      "/srv/conda/envs/notebook/lib/python3.10/site-packages/xarray/coding/times.py:699: SerializationWarning: Unable to decode time axis into full numpy.datetime64 objects, continuing using cftime.datetime objects instead, reason: dates out of range\n",
      "  dtype = _decode_cf_datetime_dtype(data, units, calendar, self.use_cftime)\n",
      "/srv/conda/envs/notebook/lib/python3.10/site-packages/xarray/core/indexing.py:524: SerializationWarning: Unable to decode time axis into full numpy.datetime64 objects, continuing using cftime.datetime objects instead, reason: dates out of range\n",
      "  return np.asarray(array[self.key], dtype=None)\n",
      "/srv/conda/envs/notebook/lib/python3.10/site-packages/xarray/coding/times.py:699: SerializationWarning: Unable to decode time axis into full numpy.datetime64 objects, continuing using cftime.datetime objects instead, reason: dates out of range\n",
      "  dtype = _decode_cf_datetime_dtype(data, units, calendar, self.use_cftime)\n",
      "/srv/conda/envs/notebook/lib/python3.10/site-packages/xarray/coding/times.py:699: SerializationWarning: Unable to decode time axis into full numpy.datetime64 objects, continuing using cftime.datetime objects instead, reason: dates out of range\n",
      "  dtype = _decode_cf_datetime_dtype(data, units, calendar, self.use_cftime)\n",
      "/srv/conda/envs/notebook/lib/python3.10/site-packages/xarray/core/indexing.py:524: SerializationWarning: Unable to decode time axis into full numpy.datetime64 objects, continuing using cftime.datetime objects instead, reason: dates out of range\n",
      "  return np.asarray(array[self.key], dtype=None)\n"
     ]
    }
   ],
   "source": [
    "df = pd.read_csv('https://storage.googleapis.com/cmip6/cmip6-zarr-consolidated-stores.csv')\n",
    "df.head()\n",
    "\n",
    "def get_df(invar):\n",
    "# this only needs to be created once\n",
    "    gcs = gcsfs.GCSFileSystem(token='anon')\n",
    "\n",
    "# get the path to a specific zarr store (the first one from the dataframe above)\n",
    "    zstore = invar.zstore.values[0]\n",
    "\n",
    "# create a mutable-mapping-style interface to the store\n",
    "    mapper = gcs.get_mapper(zstore)\n",
    "\n",
    "# open it using xarray and zarr\n",
    "    outvar = xr.open_zarr(mapper, consolidated=True)\n",
    "\n",
    "    return outvar\n",
    "\n",
    "model_names=['ACCESS-CM2','ACCESS-ESM1-5','CanESM5-CanOE','CanESM5','CESM2-WACCM','CESM2',\\\n",
    "             'CNRM-CM6-1','CNRM-ESM2-1','EC-Earth3','EC-Earth3-Veg','FGOALS-g3',\\\n",
    "                 'FIO-ESM-2-0','HadGEM3-GC31-LL','HadGEM3-GC31-MM','IPSL-CM6A-LR','KACE-1-0-G',\\\n",
    "                    'MIROC6','MIROC-ES2L', 'MPI-ESM1-2-LR','UKESM1-0-LL']\n",
    "\n",
    "\n",
    "for x in range(0,len(model_names)):\n",
    "\n",
    "\n",
    "    \n",
    "    model_name='\"'+model_names[x]+'\"'\n",
    "    experiment='\"piControl\"'\n",
    "\n",
    "    test='source_id == '+ model_name +' & activity_id==\"CMIP\" & table_id == \"Omon\" & variable_id == \"thetao\" & experiment_id == '+experiment\n",
    "\n",
    " #   theta = df.query('source_id =='+ model_name +' & table_id == \"Amon\" & variable_id == \"ts\" & experiment_id =='+ experiment+'& member_id == \"r1i1p1f1\"')\n",
    " #   tauu=df.query('source_id =='+ model_name +'& table_id == \"Amon\" & variable_id == \"tauu\" & experiment_id =='+ experiment+'& member_id == \"r1i1p1f1\"')\n",
    "    theta = df.query('source_id =='+ model_name +' & table_id == \"Amon\" & variable_id == \"ts\" & experiment_id =='+ experiment)\n",
    "   # tauu=df.query('source_id =='+ model_name +'& table_id == \"Amon\" & variable_id == \"tauu\" & experiment_id =='+ experiment)\n",
    "\n",
    "    import xesmf as xe # I use xesmf to regrid from the ocean curvelinear to lat/lon grid\n",
    "\n",
    "    theta_pi=get_df(theta)\n",
    "    theta_trop=theta_pi.sel(lon=slice(140,280)).sel(lat=slice(-15,15)).isel(time=slice(0,200*12))\n",
    "    sst_low=theta_trop['ts'].assign_coords(time=range(0,len(theta_trop.time)))\n",
    "    sst_low.load()\n",
    "    sst_low= dsp.bandpass(sst_low,1/(10*12),1/(1.5*12),dim='time')\n",
    "\n",
    "    sst_low=sst_low.transpose(\"time\", \"lon\", \"lat\")\n",
    "\n",
    "    solver = Eof(sst_low)\n",
    "\n",
    "    eofs = solver.eofs(neofs=2)\n",
    "    pcs = solver.pcs(npcs=2)\n",
    "    pcs = (pcs-pcs.mean('time'))/pcs.std('time')    \n",
    "    eofs=eofs.transpose(\"lat\", \"lon\",'mode')\n",
    "    \n",
    "    model_name='\"'+model_names[x]+'\"'\n",
    "    experiment='\"1pctCO2\"'\n",
    "\n",
    "    test='source_id == '+ model_name +' & activity_id==\"CMIP\" & table_id == \"Omon\" & variable_id == \"thetao\" & experiment_id == '+experiment\n",
    "\n",
    " #   theta = df.query('source_id =='+ model_name +' & table_id == \"Amon\" & variable_id == \"ts\" & experiment_id =='+ experiment+'& member_id == \"r1i1p1f1\"')\n",
    " #   tauu=df.query('source_id =='+ model_name +'& table_id == \"Amon\" & variable_id == \"tauu\" & experiment_id =='+ experiment+'& member_id == \"r1i1p1f1\"')\n",
    "    theta = df.query('source_id =='+ model_name +' & table_id == \"Amon\" & variable_id == \"ts\" & experiment_id =='+ experiment)\n",
    "   # tauu=df.query('source_id =='+ model_name +'& table_id == \"Amon\" & variable_id == \"tauu\" & experiment_id =='+ experiment)\n",
    "\n",
    "    import xesmf as xe # I use xesmf to regrid from the ocean curvelinear to lat/lon grid\n",
    "\n",
    "    theta_pi=get_df(theta)\n",
    "    theta_trop=theta_pi.sel(lon=slice(140,280)).sel(lat=slice(-15,15))\n",
    "    sst_low=theta_trop['ts'].assign_coords(time=range(0,len(theta_trop.time)))\n",
    "    sst_low.load()\n",
    "    sst_low= dsp.bandpass(sst_low,1/(10*12),1/(1.5*12),dim='time')\n",
    "\n",
    "\n",
    "    sst_low=sst_low.transpose(\"time\", \"lon\", \"lat\")\n",
    "\n",
    "    pseudo_pcs = solver.projectField(sst_low, neofs=2)\n",
    "\n",
    "\n",
    "    E_index=(pseudo_pcs.sel(mode=0)+pseudo_pcs.sel(mode=1))#**(-1/2)\n",
    "    E_index=E_index/math.sqrt(2)\n",
    "\n",
    "    E_index.to_netcdf('C_index_proj'+model_names[x]+'_1pct.nc')\n",
    "  "
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 8,
   "id": "dc4473a4-f2fe-45af-9d13-3ce1e3fac315",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "/srv/conda/envs/notebook/lib/python3.10/site-packages/xarray/coding/times.py:699: SerializationWarning: Unable to decode time axis into full numpy.datetime64 objects, continuing using cftime.datetime objects instead, reason: dates out of range\n",
      "  dtype = _decode_cf_datetime_dtype(data, units, calendar, self.use_cftime)\n",
      "/srv/conda/envs/notebook/lib/python3.10/site-packages/xarray/coding/times.py:150: SerializationWarning: Ambiguous reference date string: 950-01-01. The first value is assumed to be the year hence will be padded with zeros to remove the ambiguity (the padded reference date string is: 0950-01-01). To remove this message, remove the ambiguity by padding your reference date strings with zeros.\n",
      "  warnings.warn(warning_msg, SerializationWarning)\n",
      "/srv/conda/envs/notebook/lib/python3.10/site-packages/xarray/core/indexing.py:524: SerializationWarning: Unable to decode time axis into full numpy.datetime64 objects, continuing using cftime.datetime objects instead, reason: dates out of range\n",
      "  return np.asarray(array[self.key], dtype=None)\n",
      "/srv/conda/envs/notebook/lib/python3.10/site-packages/xarray/coding/times.py:699: SerializationWarning: Unable to decode time axis into full numpy.datetime64 objects, continuing using cftime.datetime objects instead, reason: dates out of range\n",
      "  dtype = _decode_cf_datetime_dtype(data, units, calendar, self.use_cftime)\n",
      "/srv/conda/envs/notebook/lib/python3.10/site-packages/xarray/coding/times.py:150: SerializationWarning: Ambiguous reference date string: 950-01-01. The first value is assumed to be the year hence will be padded with zeros to remove the ambiguity (the padded reference date string is: 0950-01-01). To remove this message, remove the ambiguity by padding your reference date strings with zeros.\n",
      "  warnings.warn(warning_msg, SerializationWarning)\n",
      "/srv/conda/envs/notebook/lib/python3.10/site-packages/xarray/core/indexing.py:524: SerializationWarning: Unable to decode time axis into full numpy.datetime64 objects, continuing using cftime.datetime objects instead, reason: dates out of range\n",
      "  return np.asarray(array[self.key], dtype=None)\n",
      "/srv/conda/envs/notebook/lib/python3.10/site-packages/xarray/coding/times.py:699: SerializationWarning: Unable to decode time axis into full numpy.datetime64 objects, continuing using cftime.datetime objects instead, reason: dates out of range\n",
      "  dtype = _decode_cf_datetime_dtype(data, units, calendar, self.use_cftime)\n",
      "/srv/conda/envs/notebook/lib/python3.10/site-packages/xarray/core/indexing.py:524: SerializationWarning: Unable to decode time axis into full numpy.datetime64 objects, continuing using cftime.datetime objects instead, reason: dates out of range\n",
      "  return np.asarray(array[self.key], dtype=None)\n",
      "/srv/conda/envs/notebook/lib/python3.10/site-packages/xarray/coding/times.py:699: SerializationWarning: Unable to decode time axis into full numpy.datetime64 objects, continuing using cftime.datetime objects instead, reason: dates out of range\n",
      "  dtype = _decode_cf_datetime_dtype(data, units, calendar, self.use_cftime)\n",
      "/srv/conda/envs/notebook/lib/python3.10/site-packages/xarray/coding/times.py:150: SerializationWarning: Ambiguous reference date string: 101-01-01. The first value is assumed to be the year hence will be padded with zeros to remove the ambiguity (the padded reference date string is: 0101-01-01). To remove this message, remove the ambiguity by padding your reference date strings with zeros.\n",
      "  warnings.warn(warning_msg, SerializationWarning)\n",
      "/srv/conda/envs/notebook/lib/python3.10/site-packages/xarray/core/indexing.py:524: SerializationWarning: Unable to decode time axis into full numpy.datetime64 objects, continuing using cftime.datetime objects instead, reason: dates out of range\n",
      "  return np.asarray(array[self.key], dtype=None)\n",
      "/srv/conda/envs/notebook/lib/python3.10/site-packages/xarray/coding/times.py:699: SerializationWarning: Unable to decode time axis into full numpy.datetime64 objects, continuing using cftime.datetime objects instead, reason: dates out of range\n",
      "  dtype = _decode_cf_datetime_dtype(data, units, calendar, self.use_cftime)\n",
      "/srv/conda/envs/notebook/lib/python3.10/site-packages/xarray/core/indexing.py:524: SerializationWarning: Unable to decode time axis into full numpy.datetime64 objects, continuing using cftime.datetime objects instead, reason: dates out of range\n",
      "  return np.asarray(array[self.key], dtype=None)\n",
      "/srv/conda/envs/notebook/lib/python3.10/site-packages/xarray/coding/times.py:699: SerializationWarning: Unable to decode time axis into full numpy.datetime64 objects, continuing using cftime.datetime objects instead, reason: dates out of range\n",
      "  dtype = _decode_cf_datetime_dtype(data, units, calendar, self.use_cftime)\n",
      "/srv/conda/envs/notebook/lib/python3.10/site-packages/xarray/coding/times.py:699: SerializationWarning: Unable to decode time axis into full numpy.datetime64 objects, continuing using cftime.datetime objects instead, reason: dates out of range\n",
      "  dtype = _decode_cf_datetime_dtype(data, units, calendar, self.use_cftime)\n",
      "/srv/conda/envs/notebook/lib/python3.10/site-packages/xarray/core/indexing.py:524: SerializationWarning: Unable to decode time axis into full numpy.datetime64 objects, continuing using cftime.datetime objects instead, reason: dates out of range\n",
      "  return np.asarray(array[self.key], dtype=None)\n",
      "/srv/conda/envs/notebook/lib/python3.10/site-packages/xarray/coding/times.py:699: SerializationWarning: Unable to decode time axis into full numpy.datetime64 objects, continuing using cftime.datetime objects instead, reason: dates out of range\n",
      "  dtype = _decode_cf_datetime_dtype(data, units, calendar, self.use_cftime)\n",
      "/srv/conda/envs/notebook/lib/python3.10/site-packages/xarray/coding/times.py:699: SerializationWarning: Unable to decode time axis into full numpy.datetime64 objects, continuing using cftime.datetime objects instead, reason: dates out of range\n",
      "  dtype = _decode_cf_datetime_dtype(data, units, calendar, self.use_cftime)\n",
      "/srv/conda/envs/notebook/lib/python3.10/site-packages/xarray/core/indexing.py:524: SerializationWarning: Unable to decode time axis into full numpy.datetime64 objects, continuing using cftime.datetime objects instead, reason: dates out of range\n",
      "  return np.asarray(array[self.key], dtype=None)\n",
      "/srv/conda/envs/notebook/lib/python3.10/site-packages/xarray/coding/times.py:699: SerializationWarning: Unable to decode time axis into full numpy.datetime64 objects, continuing using cftime.datetime objects instead, reason: dates out of range\n",
      "  dtype = _decode_cf_datetime_dtype(data, units, calendar, self.use_cftime)\n",
      "/srv/conda/envs/notebook/lib/python3.10/site-packages/xarray/core/indexing.py:524: SerializationWarning: Unable to decode time axis into full numpy.datetime64 objects, continuing using cftime.datetime objects instead, reason: dates out of range\n",
      "  return np.asarray(array[self.key], dtype=None)\n",
      "/srv/conda/envs/notebook/lib/python3.10/site-packages/xarray/coding/times.py:699: SerializationWarning: Unable to decode time axis into full numpy.datetime64 objects, continuing using cftime.datetime objects instead, reason: dates out of range\n",
      "  dtype = _decode_cf_datetime_dtype(data, units, calendar, self.use_cftime)\n",
      "/srv/conda/envs/notebook/lib/python3.10/site-packages/xarray/core/indexing.py:524: SerializationWarning: Unable to decode time axis into full numpy.datetime64 objects, continuing using cftime.datetime objects instead, reason: dates out of range\n",
      "  return np.asarray(array[self.key], dtype=None)\n",
      "/srv/conda/envs/notebook/lib/python3.10/site-packages/xarray/coding/times.py:699: SerializationWarning: Unable to decode time axis into full numpy.datetime64 objects, continuing using cftime.datetime objects instead, reason: dates out of range\n",
      "  dtype = _decode_cf_datetime_dtype(data, units, calendar, self.use_cftime)\n",
      "/srv/conda/envs/notebook/lib/python3.10/site-packages/xarray/coding/times.py:699: SerializationWarning: Unable to decode time axis into full numpy.datetime64 objects, continuing using cftime.datetime objects instead, reason: dates out of range\n",
      "  dtype = _decode_cf_datetime_dtype(data, units, calendar, self.use_cftime)\n",
      "/srv/conda/envs/notebook/lib/python3.10/site-packages/xarray/core/indexing.py:524: SerializationWarning: Unable to decode time axis into full numpy.datetime64 objects, continuing using cftime.datetime objects instead, reason: dates out of range\n",
      "  return np.asarray(array[self.key], dtype=None)\n",
      "/srv/conda/envs/notebook/lib/python3.10/site-packages/xarray/coding/times.py:699: SerializationWarning: Unable to decode time axis into full numpy.datetime64 objects, continuing using cftime.datetime objects instead, reason: dates out of range\n",
      "  dtype = _decode_cf_datetime_dtype(data, units, calendar, self.use_cftime)\n",
      "/srv/conda/envs/notebook/lib/python3.10/site-packages/xarray/coding/times.py:699: SerializationWarning: Unable to decode time axis into full numpy.datetime64 objects, continuing using cftime.datetime objects instead, reason: dates out of range\n",
      "  dtype = _decode_cf_datetime_dtype(data, units, calendar, self.use_cftime)\n",
      "/srv/conda/envs/notebook/lib/python3.10/site-packages/xarray/core/indexing.py:524: SerializationWarning: Unable to decode time axis into full numpy.datetime64 objects, continuing using cftime.datetime objects instead, reason: dates out of range\n",
      "  return np.asarray(array[self.key], dtype=None)\n"
     ]
    }
   ],
   "source": [
    "df = pd.read_csv('https://storage.googleapis.com/cmip6/cmip6-zarr-consolidated-stores.csv')\n",
    "df.head()\n",
    "\n",
    "def get_df(invar):\n",
    "# this only needs to be created once\n",
    "    gcs = gcsfs.GCSFileSystem(token='anon')\n",
    "\n",
    "# get the path to a specific zarr store (the first one from the dataframe above)\n",
    "    zstore = invar.zstore.values[0]\n",
    "\n",
    "# create a mutable-mapping-style interface to the store\n",
    "    mapper = gcs.get_mapper(zstore)\n",
    "\n",
    "# open it using xarray and zarr\n",
    "    outvar = xr.open_zarr(mapper, consolidated=True)\n",
    "\n",
    "    return outvar\n",
    "\n",
    "model_names=['ACCESS-CM2','ACCESS-ESM1-5','CanESM5','CESM2-WACCM','CESM2',\\\n",
    "             'CNRM-CM6-1','CNRM-ESM2-1','EC-Earth3','EC-Earth3-Veg','FGOALS-g3',\\\n",
    "                 'FIO-ESM-2-0','HadGEM3-GC31-LL','HadGEM3-GC31-MM','IPSL-CM6A-LR','KACE-1-0-G',\\\n",
    "                    'MIROC6','MIROC-ES2L', 'MPI-ESM1-2-LR','UKESM1-0-LL']\n",
    "\n",
    "for x in range(0,len(model_names)):\n",
    "\n",
    "\n",
    "    \n",
    "    model_name='\"'+model_names[x]+'\"'\n",
    "    experiment='\"piControl\"'\n",
    "\n",
    "    test='source_id == '+ model_name +' & activity_id==\"CMIP\" & table_id == \"Omon\" & variable_id == \"thetao\" & experiment_id == '+experiment\n",
    "\n",
    " #   theta = df.query('source_id =='+ model_name +' & table_id == \"Amon\" & variable_id == \"ts\" & experiment_id =='+ experiment+'& member_id == \"r1i1p1f1\"')\n",
    " #   tauu=df.query('source_id =='+ model_name +'& table_id == \"Amon\" & variable_id == \"tauu\" & experiment_id =='+ experiment+'& member_id == \"r1i1p1f1\"')\n",
    "    theta = df.query('source_id =='+ model_name +' & table_id == \"Amon\" & variable_id == \"ts\" & experiment_id =='+ experiment)\n",
    "   # tauu=df.query('source_id =='+ model_name +'& table_id == \"Amon\" & variable_id == \"tauu\" & experiment_id =='+ experiment)\n",
    "\n",
    "    import xesmf as xe # I use xesmf to regrid from the ocean curvelinear to lat/lon grid\n",
    "\n",
    "    theta_pi=get_df(theta)\n",
    "    theta_trop=theta_pi.sel(lon=slice(140,280)).sel(lat=slice(-15,15)).isel(time=slice(0,200*12))\n",
    "    sst_low=theta_trop['ts'].assign_coords(time=range(0,len(theta_trop.time)))\n",
    "    sst_low.load()\n",
    "    sst_low= dsp.bandpass(sst_low,1/(10*12),1/(1.5*12),dim='time')\n",
    "\n",
    "    sst_low=sst_low.transpose(\"time\", \"lon\", \"lat\")\n",
    "\n",
    "    solver = Eof(sst_low)\n",
    "\n",
    "    eofs = solver.eofs(neofs=2)\n",
    "    pcs = solver.pcs(npcs=2)\n",
    "    pcs = (pcs-pcs.mean('time'))/pcs.std('time')   \n",
    "    eofs=eofs.transpose(\"lat\", \"lon\",'mode')\n",
    "    \n",
    "    model_name='\"'+model_names[x]+'\"'\n",
    "    experiment='\"abrupt-4xCO2\"'\n",
    "\n",
    "    test='source_id == '+ model_name +' & activity_id==\"CMIP\" & table_id == \"Omon\" & variable_id == \"thetao\" & experiment_id == '+experiment\n",
    "\n",
    " #   theta = df.query('source_id =='+ model_name +' & table_id == \"Amon\" & variable_id == \"ts\" & experiment_id =='+ experiment+'& member_id == \"r1i1p1f1\"')\n",
    " #   tauu=df.query('source_id =='+ model_name +'& table_id == \"Amon\" & variable_id == \"tauu\" & experiment_id =='+ experiment+'& member_id == \"r1i1p1f1\"')\n",
    "    theta = df.query('source_id =='+ model_name +' & table_id == \"Amon\" & variable_id == \"ts\" & experiment_id =='+ experiment)\n",
    "   # tauu=df.query('source_id =='+ model_name +'& table_id == \"Amon\" & variable_id == \"tauu\" & experiment_id =='+ experiment)\n",
    "\n",
    "    import xesmf as xe # I use xesmf to regrid from the ocean curvelinear to lat/lon grid\n",
    "\n",
    "    theta_pi=get_df(theta)\n",
    "    theta_trop=theta_pi.sel(lon=slice(140,280)).sel(lat=slice(-15,15))\n",
    "    sst_low=theta_trop['ts'].assign_coords(time=range(0,len(theta_trop.time)))\n",
    "    sst_low.load()\n",
    "    sst_low= dsp.bandpass(sst_low,1/(10*12),1/(1.5*12),dim='time')\n",
    "\n",
    "    sst_low=sst_low.transpose(\"time\", \"lon\", \"lat\")\n",
    "\n",
    "    pseudo_pcs = solver.projectField(sst_low, neofs=2)\n",
    "\n",
    "\n",
    "    E_index=(pseudo_pcs.sel(mode=0)+pseudo_pcs.sel(mode=1))#**(-1/2)\n",
    "    E_index=E_index/math.sqrt(2)\n",
    "\n",
    "    E_index.to_netcdf('C_index_proj'+model_names[x]+'_4x.nc')\n",
    "  "
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 9,
   "id": "9b087cda-f2f0-45bc-b865-7afb41803c09",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "/srv/conda/envs/notebook/lib/python3.10/site-packages/xarray/coding/times.py:699: SerializationWarning: Unable to decode time axis into full numpy.datetime64 objects, continuing using cftime.datetime objects instead, reason: dates out of range\n",
      "  dtype = _decode_cf_datetime_dtype(data, units, calendar, self.use_cftime)\n",
      "/srv/conda/envs/notebook/lib/python3.10/site-packages/xarray/coding/times.py:699: SerializationWarning: Unable to decode time axis into full numpy.datetime64 objects, continuing using cftime.datetime objects instead, reason: dates out of range\n",
      "  dtype = _decode_cf_datetime_dtype(data, units, calendar, self.use_cftime)\n",
      "/srv/conda/envs/notebook/lib/python3.10/site-packages/xarray/core/indexing.py:524: SerializationWarning: Unable to decode time axis into full numpy.datetime64 objects, continuing using cftime.datetime objects instead, reason: dates out of range\n",
      "  return np.asarray(array[self.key], dtype=None)\n"
     ]
    }
   ],
   "source": [
    "df = pd.read_csv('https://storage.googleapis.com/cmip6/cmip6-zarr-consolidated-stores.csv')\n",
    "df.head()\n",
    "\n",
    "def get_df(invar):\n",
    "# this only needs to be created once\n",
    "    gcs = gcsfs.GCSFileSystem(token='anon')\n",
    "\n",
    "# get the path to a specific zarr store (the first one from the dataframe above)\n",
    "    zstore = invar.zstore.values[0]\n",
    "\n",
    "# create a mutable-mapping-style interface to the store\n",
    "    mapper = gcs.get_mapper(zstore)\n",
    "\n",
    "# open it using xarray and zarr\n",
    "    outvar = xr.open_zarr(mapper, consolidated=True)\n",
    "\n",
    "    return outvar\n",
    "\n",
    "model_names=['ACCESS-CM2','ACCESS-ESM1-5','CanESM5-CanOE','CanESM5','CESM2',\\\n",
    "             'CNRM-CM6-1','CNRM-ESM2-1','EC-Earth3','EC-Earth3-Veg','FGOALS-g3',\\\n",
    "                 'FIO-ESM-2-0','IPSL-CM6A-LR','KACE-1-0-G',\\\n",
    "                    'MIROC6','MIROC-ES2L', 'MPI-ESM1-2-LR','UKESM1-0-LL']\n",
    "for x in range(0,len(model_names)):\n",
    "\n",
    "    \n",
    "    model_name='\"'+model_names[x]+'\"'\n",
    "    experiment='\"ssp126\"'\n",
    "\n",
    "    test='source_id == '+ model_name +' & activity_id==\"CMIP\" & table_id == \"Omon\" & variable_id == \"thetao\" & experiment_id == '+experiment\n",
    "\n",
    " #   theta = df.query('source_id =='+ model_name +' & table_id == \"Amon\" & variable_id == \"ts\" & experiment_id =='+ experiment+'& member_id == \"r1i1p1f1\"')\n",
    " #   tauu=df.query('source_id =='+ model_name +'& table_id == \"Amon\" & variable_id == \"tauu\" & experiment_id =='+ experiment+'& member_id == \"r1i1p1f1\"')\n",
    "    theta = df.query('source_id =='+ model_name +' & table_id == \"Amon\" & variable_id == \"ts\" & experiment_id =='+ experiment)\n",
    "   # tauu=df.query('source_id =='+ model_name +'& table_id == \"Amon\" & variable_id == \"tauu\" & experiment_id =='+ experiment)\n",
    "\n",
    "    import xesmf as xe # I use xesmf to regrid from the ocean curvelinear to lat/lon grid\n",
    "\n",
    "    theta_pi=get_df(theta)\n",
    "    theta_trop=theta_pi.sel(lon=slice(140,280)).sel(lat=slice(-15,15))\n",
    "    sst_low=theta_trop['ts'].assign_coords(time=range(0,len(theta_trop.time)))\n",
    "    sst_low.load()\n",
    "    sst_low= dsp.bandpass(sst_low,1/(10*12),1/(1.5*12),dim='time')\n",
    "\n",
    "    sst_low=sst_low.transpose(\"time\", \"lon\", \"lat\")\n",
    "    \n",
    "    solver = Eof(sst_low)\n",
    "\n",
    "    eofs = solver.eofs(neofs=2)\n",
    "    pcs = solver.pcs(npcs=2)\n",
    "    eofs=eofs.transpose(\"lat\", \"lon\",'mode')\n",
    "\n",
    "    E_index=(pcs.sel(mode=0)+pcs.sel(mode=1))#**(-1/2)\n",
    "    E_index=E_index/math.sqrt(2)\n",
    "\n",
    "    E_index.to_netcdf('C_index'+model_names[x]+'_ssp1_1.nc')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 10,
   "id": "cfa75c42-fd18-4313-9bea-4e3a9cd39421",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "/srv/conda/envs/notebook/lib/python3.10/site-packages/xarray/coding/times.py:699: SerializationWarning: Unable to decode time axis into full numpy.datetime64 objects, continuing using cftime.datetime objects instead, reason: dates out of range\n",
      "  dtype = _decode_cf_datetime_dtype(data, units, calendar, self.use_cftime)\n",
      "/srv/conda/envs/notebook/lib/python3.10/site-packages/xarray/coding/times.py:699: SerializationWarning: Unable to decode time axis into full numpy.datetime64 objects, continuing using cftime.datetime objects instead, reason: dates out of range\n",
      "  dtype = _decode_cf_datetime_dtype(data, units, calendar, self.use_cftime)\n",
      "/srv/conda/envs/notebook/lib/python3.10/site-packages/xarray/core/indexing.py:524: SerializationWarning: Unable to decode time axis into full numpy.datetime64 objects, continuing using cftime.datetime objects instead, reason: dates out of range\n",
      "  return np.asarray(array[self.key], dtype=None)\n"
     ]
    }
   ],
   "source": [
    "df = pd.read_csv('https://storage.googleapis.com/cmip6/cmip6-zarr-consolidated-stores.csv')\n",
    "df.head()\n",
    "\n",
    "def get_df(invar):\n",
    "# this only needs to be created once\n",
    "    gcs = gcsfs.GCSFileSystem(token='anon')\n",
    "\n",
    "# get the path to a specific zarr store (the first one from the dataframe above)\n",
    "    zstore = invar.zstore.values[1]\n",
    "\n",
    "# create a mutable-mapping-style interface to the store\n",
    "    mapper = gcs.get_mapper(zstore)\n",
    "\n",
    "# open it using xarray and zarr\n",
    "    outvar = xr.open_zarr(mapper, consolidated=True)\n",
    "\n",
    "    return outvar\n",
    "\n",
    "model_names=['ACCESS-CM2','ACCESS-ESM1-5','CanESM5-CanOE','CanESM5','CESM2',\\\n",
    "             'CNRM-CM6-1','CNRM-ESM2-1','EC-Earth3','EC-Earth3-Veg','FGOALS-g3',\\\n",
    "                 'FIO-ESM-2-0','IPSL-CM6A-LR','KACE-1-0-G',\\\n",
    "                    'MIROC6','MIROC-ES2L', 'MPI-ESM1-2-LR','UKESM1-0-LL']\n",
    "for x in range(0,len(model_names)):\n",
    "\n",
    "    \n",
    "    model_name='\"'+model_names[x]+'\"'\n",
    "    experiment='\"ssp126\"'\n",
    "\n",
    "    test='source_id == '+ model_name +' & activity_id==\"CMIP\" & table_id == \"Omon\" & variable_id == \"thetao\" & experiment_id == '+experiment\n",
    "\n",
    " #   theta = df.query('source_id =='+ model_name +' & table_id == \"Amon\" & variable_id == \"ts\" & experiment_id =='+ experiment+'& member_id == \"r1i1p1f1\"')\n",
    " #   tauu=df.query('source_id =='+ model_name +'& table_id == \"Amon\" & variable_id == \"tauu\" & experiment_id =='+ experiment+'& member_id == \"r1i1p1f1\"')\n",
    "    theta = df.query('source_id =='+ model_name +' & table_id == \"Amon\" & variable_id == \"ts\" & experiment_id =='+ experiment)\n",
    "   # tauu=df.query('source_id =='+ model_name +'& table_id == \"Amon\" & variable_id == \"tauu\" & experiment_id =='+ experiment)\n",
    "\n",
    "    import xesmf as xe # I use xesmf to regrid from the ocean curvelinear to lat/lon grid\n",
    "\n",
    "    theta_pi=get_df(theta)\n",
    "    theta_trop=theta_pi.sel(lon=slice(140,280)).sel(lat=slice(-15,15))\n",
    "    sst_low=theta_trop['ts'].assign_coords(time=range(0,len(theta_trop.time)))\n",
    "    sst_low.load()\n",
    "    sst_low= dsp.bandpass(sst_low,1/(10*12),1/(1.5*12),dim='time')\n",
    "\n",
    "    sst_low=sst_low.transpose(\"time\", \"lon\", \"lat\")\n",
    "\n",
    "    solver = Eof(sst_low)\n",
    "\n",
    "    eofs = solver.eofs(neofs=2)\n",
    "    pcs = solver.pcs(npcs=2)\n",
    "    eofs=eofs.transpose(\"lat\", \"lon\",'mode')\n",
    "\n",
    "    E_index=(pcs.sel(mode=0)+pcs.sel(mode=1))#**(-1/2)\n",
    "    E_index=E_index/math.sqrt(2)\n",
    "\n",
    "    E_index.to_netcdf('C_index'+model_names[x]+'_ssp1_2.nc')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 11,
   "id": "80b18b2f-9c36-4350-be7a-69a678251355",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "/srv/conda/envs/notebook/lib/python3.10/site-packages/xarray/coding/times.py:699: SerializationWarning: Unable to decode time axis into full numpy.datetime64 objects, continuing using cftime.datetime objects instead, reason: dates out of range\n",
      "  dtype = _decode_cf_datetime_dtype(data, units, calendar, self.use_cftime)\n",
      "/srv/conda/envs/notebook/lib/python3.10/site-packages/xarray/coding/times.py:699: SerializationWarning: Unable to decode time axis into full numpy.datetime64 objects, continuing using cftime.datetime objects instead, reason: dates out of range\n",
      "  dtype = _decode_cf_datetime_dtype(data, units, calendar, self.use_cftime)\n",
      "/srv/conda/envs/notebook/lib/python3.10/site-packages/xarray/core/indexing.py:524: SerializationWarning: Unable to decode time axis into full numpy.datetime64 objects, continuing using cftime.datetime objects instead, reason: dates out of range\n",
      "  return np.asarray(array[self.key], dtype=None)\n",
      "/srv/conda/envs/notebook/lib/python3.10/site-packages/xarray/coding/times.py:699: SerializationWarning: Unable to decode time axis into full numpy.datetime64 objects, continuing using cftime.datetime objects instead, reason: dates out of range\n",
      "  dtype = _decode_cf_datetime_dtype(data, units, calendar, self.use_cftime)\n",
      "/srv/conda/envs/notebook/lib/python3.10/site-packages/xarray/coding/times.py:699: SerializationWarning: Unable to decode time axis into full numpy.datetime64 objects, continuing using cftime.datetime objects instead, reason: dates out of range\n",
      "  dtype = _decode_cf_datetime_dtype(data, units, calendar, self.use_cftime)\n",
      "/srv/conda/envs/notebook/lib/python3.10/site-packages/xarray/core/indexing.py:524: SerializationWarning: Unable to decode time axis into full numpy.datetime64 objects, continuing using cftime.datetime objects instead, reason: dates out of range\n",
      "  return np.asarray(array[self.key], dtype=None)\n"
     ]
    }
   ],
   "source": [
    "df = pd.read_csv('https://storage.googleapis.com/cmip6/cmip6-zarr-consolidated-stores.csv')\n",
    "df.head()\n",
    "\n",
    "def get_df(invar):\n",
    "# this only needs to be created once\n",
    "    gcs = gcsfs.GCSFileSystem(token='anon')\n",
    "\n",
    "# get the path to a specific zarr store (the first one from the dataframe above)\n",
    "    zstore = invar.zstore.values[2]\n",
    "\n",
    "# create a mutable-mapping-style interface to the store\n",
    "    mapper = gcs.get_mapper(zstore)\n",
    "\n",
    "# open it using xarray and zarr\n",
    "    outvar = xr.open_zarr(mapper, consolidated=True)\n",
    "\n",
    "    return outvar\n",
    "\n",
    "model_names=['ACCESS-CM2','ACCESS-ESM1-5','CanESM5-CanOE','CanESM5','CESM2',\\\n",
    "             'CNRM-CM6-1','CNRM-ESM2-1','EC-Earth3','EC-Earth3-Veg','FGOALS-g3',\\\n",
    "                 'FIO-ESM-2-0','IPSL-CM6A-LR','KACE-1-0-G',\\\n",
    "                    'MIROC6','MIROC-ES2L', 'MPI-ESM1-2-LR','UKESM1-0-LL']\n",
    "for x in range(0,len(model_names)):\n",
    "\n",
    "    \n",
    "    model_name='\"'+model_names[x]+'\"'\n",
    "    experiment='\"ssp126\"'\n",
    "\n",
    "    test='source_id == '+ model_name +' & activity_id==\"CMIP\" & table_id == \"Omon\" & variable_id == \"thetao\" & experiment_id == '+experiment\n",
    "\n",
    " #   theta = df.query('source_id =='+ model_name +' & table_id == \"Amon\" & variable_id == \"ts\" & experiment_id =='+ experiment+'& member_id == \"r1i1p1f1\"')\n",
    " #   tauu=df.query('source_id =='+ model_name +'& table_id == \"Amon\" & variable_id == \"tauu\" & experiment_id =='+ experiment+'& member_id == \"r1i1p1f1\"')\n",
    "    theta = df.query('source_id =='+ model_name +' & table_id == \"Amon\" & variable_id == \"ts\" & experiment_id =='+ experiment)\n",
    "   # tauu=df.query('source_id =='+ model_name +'& table_id == \"Amon\" & variable_id == \"tauu\" & experiment_id =='+ experiment)\n",
    "\n",
    "    import xesmf as xe # I use xesmf to regrid from the ocean curvelinear to lat/lon grid\n",
    "\n",
    "    theta_pi=get_df(theta)\n",
    "    theta_trop=theta_pi.sel(lon=slice(140,280)).sel(lat=slice(-15,15))\n",
    "    sst_low=theta_trop['ts'].assign_coords(time=range(0,len(theta_trop.time)))\n",
    "    sst_low.load()\n",
    "    sst_low= dsp.bandpass(sst_low,1/(10*12),1/(1.5*12),dim='time')\n",
    "\n",
    "    sst_low=sst_low.transpose(\"time\", \"lon\", \"lat\")\n",
    "\n",
    "    solver = Eof(sst_low)\n",
    "\n",
    "    eofs = solver.eofs(neofs=2)\n",
    "    pcs = solver.pcs(npcs=2)\n",
    "    eofs=eofs.transpose(\"lat\", \"lon\",'mode')\n",
    "\n",
    "    E_index=(pcs.sel(mode=0)+pcs.sel(mode=1))#**(-1/2)\n",
    "    E_index=E_index/math.sqrt(2)\n",
    "\n",
    "    E_index.to_netcdf('C_index'+model_names[x]+'_ssp1_3.nc')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "409a037d-d018-4144-855b-b10ac2163264",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.10.8"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
